// <auto-generated />
using System;
using BijliSaver.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BijliSaver.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714212643_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BijliSaver.Api.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Arrears")
                        .HasColumnType("numeric")
                        .HasColumnName("arrears");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentBill")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bill");

                    b.Property<short>("DiscoId")
                        .HasColumnType("smallint")
                        .HasColumnName("disco_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly?>("FpaMonth")
                        .HasColumnType("date")
                        .HasColumnName("fpa_month");

                    b.Property<decimal?>("FpaRate")
                        .HasColumnType("numeric")
                        .HasColumnName("fpa_rate");

                    b.Property<decimal?>("GopRate")
                        .HasColumnType("numeric")
                        .HasColumnName("gop_rate");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("LpSurcharge")
                        .HasColumnType("numeric")
                        .HasColumnName("lp_surcharge");

                    b.Property<decimal?>("OcrConfidence")
                        .HasColumnType("numeric")
                        .HasColumnName("ocr_confidence");

                    b.Property<string>("OcrRaw")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_raw");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_status");

                    b.Property<decimal?>("PayableAfterDue")
                        .HasColumnType("numeric")
                        .HasColumnName("payable_after_due");

                    b.Property<decimal?>("PayableWithinDue")
                        .HasColumnType("numeric")
                        .HasColumnName("payable_within_due");

                    b.Property<bool>("ReadingIsEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("reading_is_estimated");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text")
                        .HasColumnName("reference_no");

                    b.Property<string>("TariffCode")
                        .HasColumnType("text")
                        .HasColumnName("tariff_code");

                    b.Property<decimal?>("TotalFpa")
                        .HasColumnType("numeric")
                        .HasColumnName("total_fpa");

                    b.Property<int?>("UnitsConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("units_consumed");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillCharge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<short?>("ChargeDefId")
                        .HasColumnType("smallint")
                        .HasColumnName("charge_def_id");

                    b.Property<string>("RawLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_label");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ChargeDefId");

                    b.ToTable("bill_charges", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_estimated");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<int?>("Units")
                        .HasColumnType("integer")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("bill_history_entries", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillInsight", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("ApplianceSummary")
                        .HasColumnType("text")
                        .HasColumnName("appliance_summary");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<decimal?>("EnergyTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_total");

                    b.Property<bool>("HasArrears")
                        .HasColumnType("boolean")
                        .HasColumnName("has_arrears");

                    b.Property<decimal?>("NextSlabPenalty")
                        .HasColumnType("numeric")
                        .HasColumnName("next_slab_penalty");

                    b.Property<decimal?>("PredictedNextAmt")
                        .HasColumnType("numeric")
                        .HasColumnName("predicted_next_amt");

                    b.Property<string>("PredictionBasis")
                        .HasColumnType("text")
                        .HasColumnName("prediction_basis");

                    b.Property<string>("SavingsTip")
                        .HasColumnType("text")
                        .HasColumnName("savings_tip");

                    b.Property<int?>("SlabReached")
                        .HasColumnType("integer")
                        .HasColumnName("slab_reached");

                    b.Property<decimal?>("TaxPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal?>("TaxTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_total");

                    b.Property<int?>("UnitsToNextSlab")
                        .HasColumnType("integer")
                        .HasColumnName("units_to_next_slab");

                    b.HasKey("BillId");

                    b.ToTable("bill_insights", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.ChargeDefinition", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("CanBeNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("can_be_negative");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExplanationEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_en");

                    b.Property<string>("ExplanationUr")
                        .HasColumnType("text")
                        .HasColumnName("explanation_ur");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("charge_definitions", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.Disco", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("discos", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.TariffSlab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DiscoId")
                        .HasColumnType("smallint")
                        .HasColumnName("disco_id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_protected");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("rate_per_unit");

                    b.Property<int?>("SlabMaxUnits")
                        .HasColumnType("integer")
                        .HasColumnName("slab_max_units");

                    b.Property<int>("SlabMinUnits")
                        .HasColumnType("integer")
                        .HasColumnName("slab_min_units");

                    b.Property<string>("TariffCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tariff_code");

                    b.HasKey("Id");

                    b.ToTable("tariff_slabs", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillCharge", b =>
                {
                    b.HasOne("BijliSaver.Api.Models.Bill", null)
                        .WithMany("Charges")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BijliSaver.Api.Models.ChargeDefinition", "ChargeDef")
                        .WithMany()
                        .HasForeignKey("ChargeDefId");

                    b.Navigation("ChargeDef");
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillHistoryEntry", b =>
                {
                    b.HasOne("BijliSaver.Api.Models.Bill", null)
                        .WithMany("HistoryEntries")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BijliSaver.Api.Models.BillInsight", b =>
                {
                    b.HasOne("BijliSaver.Api.Models.Bill", null)
                        .WithOne("Insight")
                        .HasForeignKey("BijliSaver.Api.Models.BillInsight", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BijliSaver.Api.Models.Bill", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("HistoryEntries");

                    b.Navigation("Insight");
                });
#pragma warning restore 612, 618
        }
    }
}
